# Data

## Description

For this project, we are using Post-Secondary Employment Outcomes (PSEO) datasets that contain earnings and employment outcomes for graduates.

### Data Source
The national and state-level PSEO datasets are publicly available through the [United States Center for Economic Studies](https://lehd.ces.census.gov/data/pseo_experimental.html). Specifically, we are using the **PSEOE (earnings)** and **PSEOF (employment rates)** files from the PSEO section.

### Data Collection
The data is collected through the Longitudinal Employer-Household Dynamics (LEHD) program. This program partners with various post-secondary institutions, state agencies, and the United States Census Bureau. LEHD merges admistrative job data with the post-secondary education records from its partners to create the PSEO datasets.

### Data Format

We are working with CSV files downloaded directly from the public data access page. The national-level datasets contains approximately **564,000 records and 36 columns**, covering aggregated **earnings and employment outcomes** for graduates **1 year, 5 years, and 10 years post-graduation** (when available). The main identifiers in the dataset include:  

- **Institution**  
- **Degree Level**  
- **Degree Field**  
- **Cohort Graduation Year**  


#### Mappings for Identifiers:

Please note that we enrich this data for visualization and analysis by mapping ID values to string values using external sources.

- **Institution (OPEID):** [Post-Secondary Institutions with OPEID](https://collegefutures.org/wp-content/uploads/2015/04/post-secondary-institutions-with-unitid.xlsx)  
- **Degree Field (CIPCODE):** [CIP Code Table](https://nces.ed.gov/ipeds/cipcode/browse.aspx?y=55)  
- **Degree Level:** [NCES Degree Level Classifcations](https://nces.ed.gov/ipeds/report-your-data/data-tip-sheet-reporting-graduate-awards) | [PSEO Technical Documentation](https://lehd.ces.census.gov/doc/PSEOTechnicalDocumentation.pdf)  

### Data Coverage

The data covers the years from 2001 to 2020 as of the 2023Q20 release. New data for additional partner institutions is added irregularly, such as the June 2024 update that incorporated new universities. See the [PSEO data notices](https://lehd.ces.census.gov/doc/PSEO_data_notices.pdf) for their updates.

**Limitations**: There are regional coverage gaps in the dataset because it only includes outcomes from institutions that have partnered with the Census Bureau through the data-sharing agreements. For that reason, many states have no coverage while most others only have partial coverage. Breakdown of state-by-state coverage can be found [here](https://lehd.ces.census.gov/data/pseo_experimental.html).

### Data References/Documentation
For more details on the above, see the follow resources:

#### **PSEO Data:**

- [PSEO Data](https://lehd.ces.census.gov/data/pseo_experimental.html) (Data Download & Coverage Stats)
- [PSEO Documentation](https://lehd.ces.census.gov/data/pseo_documentation.html) (High Level Summary)
- [PSEO Technical Documentation](https://lehd.ces.census.gov/doc/PSEOTechnicalDocumentation.pdf) (Technical Details, Data Collection, Rationale)
- [PSEO Schema](https://lehd.ces.census.gov/data/schema/latest/lehd_public_use_schema.html#_identifiers_for_pseo) (4.25, 4.36, 4.37)
- [PSEO Data Notices](https://lehd.ces.census.gov/doc/PSEO_data_notices.pdf)

#### **Mapping Data**

- [Post-Secondary Institutions with OPEID](https://collegefutures.org/wp-content/uploads/2015/04/post-secondary-institutions-with-unitid.xlsx)
- [CIP Code Table](https://nces.ed.gov/ipeds/cipcode/browse.aspx?y=55)
- [NCES Degree Level Classifcations](https://nces.ed.gov/ipeds/report-your-data/data-tip-sheet-reporting-graduate-awards)

## Missing value analysis
