# Results

In this section, we will explore several questions about the data, separated as parts.

## Preparing the Data

```{r}
library(ggplot2)
library(dplyr)
suppressPackageStartupMessages(library(tidyverse))
```

```{r}
pseoe <- read_csv("data/pseoe_all.csv", show_col_types = FALSE)
degree_mapping <- read.csv("data/label_degree_level.csv")
cipcode_mapping <- read.csv("data/label_cipcode.csv")
institution_mapping <- read.csv("data/label_institution.csv")
```

```{r}
degree_mapping <- degree_mapping |>
  mutate(degree_level = sprintf("%02d", as.integer(degree_level)))

pseoe <- pseoe |>
  left_join(degree_mapping |> select(degree_level, label), by = "degree_level") |>
  rename(degree_label = label)

cipcode_mapping$cipcode <- as.character(cipcode_mapping$cipcode)

pseoe <- pseoe |>
  left_join(cipcode_mapping |> select(cipcode, label), by = "cipcode") |>
  rename(cipcode_label = label)

pseoe <- pseoe |>
  left_join(
    institution_mapping |>
      select(institution, label, city, institution_state) |>
      rename(
        institution_label = label,
        institution_city = city
      ),
    by = "institution"
  )
```

## How do Earnings Differ by Field of Study and Degree Type?

## How have career prospects changed over the past decade?


```{r}
idcols_inst <- c(
  "agg_level_pseo", "inst_level", "institution", "degree_level",
  "cip_level", "cipcode" #, "grad_cohort", "grad_cohort_years"
)


```



```{r}
pseoe_01and16 <- pseoe |> 
                      filter(grad_cohort == "2001" | grad_cohort == "2016") |>
                      filter(status_y1_earnings %in% c(1, 2, 4, 6, 7, 9, 10, 12)) |>
                      group_by(across(all_of(idcols_inst))) |>
                      filter(all(c("2001", "2016") %in% grad_cohort))

pseoe_cipcode_change01to16 <- pseoe_01and16|>
                              group_by(cipcode_label, degree_label, grad_cohort) |>
                              summarise(mean_med_earning = mean(y1_p50_earnings, na.rm = TRUE)) |>
                              ungroup() |>
                              pivot_wider(names_from = grad_cohort, values_from = mean_med_earning, 
                                          names_prefix ="earnings_") |> # Reshape data
                              mutate(change_med_earning = earnings_2016 - earnings_2001) # Compute change

pseoe_cipcode_change01to16 <- pseoe_cipcode_change01to16 |>
  arrange(change_med_earning) |>
  select(cipcode_label, degree_label, change_med_earning)

pseoe_cipcode_change01to16 <- pseoe_cipcode_change01to16 |>
  mutate(cipcode_degree_label = paste(cipcode_label, degree_label, sep = " - "))

```


```{r}
pseoe_cipcode_change01to16
```



```{r}
ggplot(pseoe_cipcode_change01to16[1:15, ], aes(y = factor(cipcode_degree_label,
                                                                   levels = cipcode_degree_label[order(change_med_earning)]),
                                                        x = change_med_earning)) +
  geom_col() +
  ylab("CIP Code Label") +
  xlab("Change in Median Earning") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
ggplot(tail(pseoe_cipcode_change01to16, 15), aes(y = factor(cipcode_degree_label,
                                                                   levels = cipcode_degree_label[order(change_med_earning)]),
                                                        x = change_med_earning)) +
  geom_col() +
  ylab("CIP Code Label") +
  xlab("Change in Year 1 Median Earning") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
pseoe_01and16 |> filter(cipcode_label == "Pharmacy, Pharmaceutical Sciences, and Administration", degree_label == "Baccalaureate")
```

```{r}
pseoe_typedegree_change01to16 <- pseoe_01and16 |>
                              group_by(degree_label, grad_cohort) |>
                              summarise(mean_med_earning = mean(y1_p50_earnings, na.rm = TRUE)) |>
                              ungroup() |>
                              pivot_wider(names_from = grad_cohort, values_from = mean_med_earning, 
                                          names_prefix ="earnings_") |> # Reshape data
                              mutate(change_med_earning = earnings_2016 - earnings_2001) # Compute change

pseoe_typedegree_change01to16 <- pseoe_typedegree_change01to16 |>
  arrange(change_med_earning) |>
  select(degree_label, change_med_earning)
```

```{r}
ggplot(pseoe_typedegree_change01to16, aes(y = factor(degree_label,
                                                                   levels = degree_label[order(change_med_earning)]),
                                                        x = change_med_earning)) +
  geom_col() +
  ylab("Degree type") +
  xlab("Change in Year 1 Median Earning") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```



## Relation between y1 and y5 earnings

```{r}
pseoe_y1andy10 <- pseoe |>
                  filter(status_y1_earnings %in% c(1, 2, 4, 6, 7, 9, 10, 12)) |>
                  filter(status_y10_earnings %in% c(1, 2, 4, 6, 7, 9, 10, 12)) 
pseoe_y1andy10
```






```{r}

ggplot(pseoe_y1andy10, aes(x = y1_p50_earnings, y = y10_p50_earnings)) +
  geom_point(alpha=0.2) +
#  scale_fill_gradient(low="white", high="red") +
  facet_wrap(~degree_label)
```

